version: '3.8'

services:

  shipping:
    image: weaveworksdemos/shipping
    container_name: shipping
    restart: always
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411/
      - SPRING_APPLICATION_NAME=shipping
      - SPRING_SLEUTH_SAMPLER_PROBABILITY=1.0
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=prometheus,health,info
    depends_on:
      - zipkin
      - prometheus
    networks:
      - monitoring

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    ports:
      - "9411:9411"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

volumes:
  grafana-storage:

networks:
  monitoring:
    driver: bridge
