name: shippingService CI/CD

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

env:
  SERVICE_NAME: shipping
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Verify target contents
        run: ls -l target

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: shipping-jar
          path: target/shipping-0.0.1-SNAPSHOT.jar

  docker-build-push:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: shipping-jar
          path: target

      - name: Verify jar for Docker build
        run: ls -l target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/shipping:latest
            ${{ env.DOCKER_USERNAME }}/shipping:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
